version: "3.9"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"
    command: "uvicorn app.main:app --reload --host 0.0.0.0 --port 8080"